name: Client Request

on:
  workflow_dispatch:
    inputs:
      integration:
        description: Integration Payload
        required: true

jobs:
  request-client:
    runs-on: ubuntu-18.04
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2

      - name: Setup Tools
        uses: ./.github/actions/setup-tools

      - name: Setup NPM Packages
        uses: ./.github/actions/setup-yarn

      - uses: bcgov/sso-requests-actions/request@v0.23.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          api-url: ${{ secrets.WEBAPP_API_URL }}
          auth-secret: ${{ secrets.GH_SECRET }}
          tf-module-ref: dev
