name: Terraform V2 Plan

on: workflow_dispatch

env:
  TF_VERSION: 1.1.4
  TFC_WORKSPACE: xgr00q-dev-keycloak-v2
  KEYCLOAK_V2_DEV_URL: https://sso-keycloak-4-b861c7-test.apps.silver.devops.gov.bc.ca
  KEYCLOAK_V2_TEST_URL: https://sso-keycloak-5-b861c7-test.apps.silver.devops.gov.bc.ca
  KEYCLOAK_V2_PROD_URL: https://sso-keycloak-6-b861c7-test.apps.silver.devops.gov.bc.ca

jobs:
  terraform:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    env:
      API_URL: ${{secrets.WEBAPP_API_URL}}
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2

      - name: Wake Up API
        uses: fjogeleit/http-request-action@master
        with:
          url: "${{env.API_URL}}"
          method: "GET"
          customHeaders: '{"Authorization": "${{secrets.GH_SECRET}}"}'
        continue-on-error: true

      - name: Setup Terraform
        uses: ./.github/actions/setup-terraform
        with:
          context: ./terraform-v2
          tf-version: ${{ env.TF_VERSION }}
          tf-team-token: ${{ secrets.TFC_TEAM_TOKEN }}
          tf-workspace: ${{ env.TFC_WORKSPACE }}
          kc-dev-url: ${{ env.KEYCLOAK_V2_DEV_URL }}
          kc-test-url: ${{ env.KEYCLOAK_V2_TEST_URL }}
          kc-prod-url: ${{ env.KEYCLOAK_V2_PROD_URL }}
          kc-dev-secret: ${{ secrets.KEYCLOAK_V2_DEV_CLIENT_SECRET }}
          kc-test-secret: ${{ secrets.KEYCLOAK_V2_TEST_CLIENT_SECRET }}
          kc-prod-secret: ${{ secrets.KEYCLOAK_V2_PROD_CLIENT_SECRET }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ./terraform-v2
        continue-on-error: true

      - name: Truncate Terraform Plan
        run: |
          plan=$(tail -n 500 <<'EOF'
          ${{ steps.plan.outputs.stdout }}
          EOF
          )
          echo "PLAN<<EOF" >> $GITHUB_ENV
          echo "${plan}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      # NPM PACKAGES
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn dependencies in root
        run: yarn

      - name: Get PR
        id: pr
        run: |
          pr=$(curl -H "Accept: application/vnd.github.groot-preview+json" ${{github.event.pull_request._links.issue.href}})
          prstr=$(jq -c '.' <<< "$pr")
          echo "::set-output name=pr::$prstr"

      - name: Save terraform plan event
        uses: bcgov/sso-requests-actions/plan@v0.16.0
        if: contains(fromJSON(steps.pr.outputs.pr).labels.*.name, 'auto_generated')
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          api-url: "${{ env.API_URL }}"
          auth-secret: ${{ secrets.GH_SECRET }}
          plan-output: "${{ env.PLAN }}"
          plan-result: "${{ steps.plan.outcome }}"
          pr-number: "${{ github.event.number }}"
          pr-branch: "${{ github.event.pull_request.head.ref }}"
          allowed-file-changes: "3"
          allowed-file-additions: "100"
          allowed-file-deletions: "100"

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
