name: Terraform V2 State Remove

on:
  workflow_dispatch:
    inputs:
      resource_address:
        description: Resource Address
        required: true

env:
  TF_VERSION: 1.1.4
  TFC_WORKSPACE: xgr00q-dev-keycloak-v2
  KEYCLOAK_V2_DEV_URL: https://sso-keycloak-4-b861c7-test.apps.silver.devops.gov.bc.ca
  KEYCLOAK_V2_TEST_URL: https://sso-keycloak-5-b861c7-test.apps.silver.devops.gov.bc.ca
  KEYCLOAK_V2_PROD_URL: https://sso-keycloak-6-b861c7-test.apps.silver.devops.gov.bc.ca

jobs:
  terraform:
    runs-on: ubuntu-18.04
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: ./.github/actions/setup-terraform
        with:
          context: ./terraform-v2
          tf-version: ${{ env.TF_VERSION }}
          tf-team-token: ${{ secrets.TFC_TEAM_TOKEN }}
          tf-workspace: ${{ env.TFC_WORKSPACE }}
          kc-dev-url: ${{ env.KEYCLOAK_V2_DEV_URL }}
          kc-test-url: ${{ env.KEYCLOAK_V2_TEST_URL }}
          kc-prod-url: ${{ env.KEYCLOAK_V2_PROD_URL }}
          kc-dev-secret: ${{ secrets.KEYCLOAK_V2_DEV_CLIENT_SECRET }}
          kc-test-secret: ${{ secrets.KEYCLOAK_V2_TEST_CLIENT_SECRET }}
          kc-prod-secret: ${{ secrets.KEYCLOAK_V2_PROD_CLIENT_SECRET }}

        # see https://www.terraform.io/cli/commands/state/rm
      - name: Terraform State Remove
        id: destroy
        run: |
          address=${{ github.event.inputs.resource_address }}
          echo "$address"
          terraform state rm "$address"
        working-directory: ./terraform-v2
