name: Terraform V2 Apply

on: workflow_dispatch

env:
  TF_VERSION: 1.1.4
  KEYCLOAK_V2_DEV_URL: https://sso-keycloak-4-b861c7-test.apps.silver.devops.gov.bc.ca
  KEYCLOAK_V2_TEST_URL: https://sso-keycloak-5-b861c7-test.apps.silver.devops.gov.bc.ca
  KEYCLOAK_V2_PROD_URL: https://sso-keycloak-6-b861c7-test.apps.silver.devops.gov.bc.ca

jobs:
  terraform:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
    - uses: hmarr/debug-action@v2
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: bcgov/sso-requests-actions/actions/setup-terraform@v0.45.0
      with:
        context: ./terraform-v2
        tf-version: ${{ env.TF_VERSION }}
        tf-s3-bucket: xgr00q-dev-keycloak
        tf-s3-bucket-key: keycloak/gold
        tf-s3-access-key: ${{ secrets.TF_S3_ACCESS_KEY }}
        tf-s3-secret-key: ${{ secrets.TF_S3_SECRET_KEY }}
        tf-s3-role-arn: ${{ secrets.TF_S3_ROLE_ARN }}
        kc-dev-url: ${{ env.KEYCLOAK_V2_DEV_URL }}
        kc-test-url: ${{ env.KEYCLOAK_V2_TEST_URL }}
        kc-prod-url: ${{ env.KEYCLOAK_V2_PROD_URL }}
        kc-dev-secret: ${{ secrets.KEYCLOAK_V2_DEV_CLIENT_SECRET }}
        kc-test-secret: ${{ secrets.KEYCLOAK_V2_TEST_CLIENT_SECRET }}
        kc-prod-secret: ${{ secrets.KEYCLOAK_V2_PROD_CLIENT_SECRET }}
        dev-github-client-id: ${{ secrets.DEV_GITHUB_CLIENT_ID }}
        dev-github-client-secret: ${{ secrets.DEV_GITHUB_CLIENT_SECRET }}
        test-github-client-id: ${{ secrets.TEST_GITHUB_CLIENT_ID }}
        test-github-client-secret: ${{ secrets.TEST_GITHUB_CLIENT_SECRET }}
        prod-github-client-id: ${{ secrets.PROD_GITHUB_CLIENT_ID }}
        prod-github-client-secret: ${{ secrets.PROD_GITHUB_CLIENT_SECRET }}
        apply: true

    - uses: bcgov/sso-requests-actions/keycloak@v0.45.0
      with:
        dev-keycloak-url: ${{ env.KEYCLOAK_V2_DEV_URL }}
        test-keycloak-url: ${{ env.KEYCLOAK_V2_TEST_URL }}
        prod-keycloak-url: ${{ env.KEYCLOAK_V2_PROD_URL }}
        dev-client-secret: ${{ secrets.KEYCLOAK_V2_DEV_CLIENT_SECRET }}
        test-client-secret: ${{ secrets.KEYCLOAK_V2_TEST_CLIENT_SECRET }}
        prod-client-secret: ${{ secrets.KEYCLOAK_V2_PROD_CLIENT_SECRET }}
        tasks: update-review-profile-config delete-unused-client-scopes
