name: Terraform State Remove

on:
  workflow_dispatch:
    inputs:
      resource_address:
        description: Resource Address
        required: true

env:
  TF_VERSION: 1.1.4
  TFC_WORKSPACE: xgr00q-dev-keycloak_dev
  KEYCLOAK_DEV_URL: https://sso-keycloak-1-b861c7-test.apps.silver.devops.gov.bc.ca
  KEYCLOAK_TEST_URL: https://sso-keycloak-2-b861c7-test.apps.silver.devops.gov.bc.ca
  KEYCLOAK_PROD_URL: https://sso-keycloak-3-b861c7-test.apps.silver.devops.gov.bc.ca

jobs:
  terraform:
    runs-on: ubuntu-18.04
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: ./terraform-v2

      - name: Terraform Variables
        run: |
          cat >"versions.tf" <<EOF
          terraform {
            backend "remote" {
              hostname     = "app.terraform.io"
              organization = "bcgov"
              workspaces {
                name = "${{ env.TFC_WORKSPACE }}"
              }
            }
          }
          EOF

          cat >"ci.auto.tfvars" <<EOF
          dev_keycloak_url="${{ env.KEYCLOAK_DEV_URL }}"
          test_keycloak_url="${{ env.KEYCLOAK_TEST_URL }}"
          prod_keycloak_url="${{ env.KEYCLOAK_PROD_URL }}"
          dev_client_secret="${{ secrets.KEYCLOAK_DEV_CLIENT_SECRET }}"
          test_client_secret="${{ secrets.KEYCLOAK_TEST_CLIENT_SECRET }}"
          prod_client_secret="${{ secrets.KEYCLOAK_PROD_CLIENT_SECRET }}"
          EOF
        working-directory: ./terraform-v2

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./terraform-v2

        # see https://www.terraform.io/cli/commands/state/rm
      - name: Terraform State Remove
        id: destroy
        run: |
          address=${{ github.event.inputs.resource_address }}
          echo "$address"
          terraform state rm "$address"
        working-directory: ./terraform-v2
