name: Terraform V2 Plan

on: workflow_dispatch

env:
  TF_VERSION: 1.1.4
  KEYCLOAK_V2_DEV_URL: https://sso-keycloak-e4ca1d-dev.apps.gold.devops.gov.bc.ca
  KEYCLOAK_V2_TEST_URL: https://sso-keycloak-e4ca1d-test.apps.gold.devops.gov.bc.ca
  KEYCLOAK_V2_PROD_URL: https://sso-keycloak-e4ca1d-prod.apps.gold.devops.gov.bc.ca

jobs:
  terraform:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
    - uses: hmarr/debug-action@v2
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: bcgov/sso-requests-actions/actions/setup-terraform@v0.60.0
      with:
        context: ./terraform-v2
        tf-version: ${{ env.TF_VERSION }}
        tf-s3-bucket: xgr00q-dev-keycloak
        tf-s3-bucket-key: keycloak/gold
        tf-s3-dynamodb-table: xgr00q-dev-state-locking
        tf-s3-access-key: ${{ secrets.TF_S3_ACCESS_KEY }}
        tf-s3-secret-key: ${{ secrets.TF_S3_SECRET_KEY }}
        tf-s3-role-arn: ${{ secrets.TF_S3_ROLE_ARN }}
        kc-provider-version: 3.10.0
        kc-dev-url: ${{ env.KEYCLOAK_V2_DEV_URL }}
        kc-test-url: ${{ env.KEYCLOAK_V2_TEST_URL }}
        kc-prod-url: ${{ env.KEYCLOAK_V2_PROD_URL }}
        kc-dev-secret: ${{ secrets.KEYCLOAK_V2_DEV_CLIENT_SECRET }}
        kc-test-secret: ${{ secrets.KEYCLOAK_V2_TEST_CLIENT_SECRET }}
        kc-prod-secret: ${{ secrets.KEYCLOAK_V2_PROD_CLIENT_SECRET }}
        dev-github-client-id: ${{ secrets.DEV_GITHUB_CLIENT_ID }}
        dev-github-client-secret: ${{ secrets.DEV_GITHUB_CLIENT_SECRET }}
        test-github-client-id: ${{ secrets.TEST_GITHUB_CLIENT_ID }}
        test-github-client-secret: ${{ secrets.TEST_GITHUB_CLIENT_SECRET }}
        prod-github-client-id: ${{ secrets.PROD_GITHUB_CLIENT_ID }}
        prod-github-client-secret: ${{ secrets.PROD_GITHUB_CLIENT_SECRET }}
        dev-verifiablecredential-client-id: ${{ secrets.DEV_VERIFIABLECREDENTIAL_CLIENT_ID }}
        dev-verifiablecredential-client-secret: ${{ secrets.DEV_VERIFIABLECREDENTIAL_CLIENT_SECRET }}
        dev-verifiablecredential-authorization-url: ${{ secrets.DEV_VERIFIABLECREDENTIAL_AUTHORIZATION_URL }}
        dev-verifiablecredential-token-url: ${{ secrets.DEV_VERIFIABLECREDENTIAL_TOKEN_URL }}
        test-verifiablecredential-client-id: ${{ secrets.TEST_VERIFIABLECREDENTIAL_CLIENT_ID }}
        test-verifiablecredential-client-secret: ${{ secrets.TEST_VERIFIABLECREDENTIAL_CLIENT_SECRET }}
        test-verifiablecredential-authorization-url: ${{ secrets.TEST_VERIFIABLECREDENTIAL_AUTHORIZATION_URL }}
        test-verifiablecredential-token-url: ${{ secrets.TEST_VERIFIABLECREDENTIAL_TOKEN_URL }}
        prod-verifiablecredential-client-id: ${{ secrets.PROD_VERIFIABLECREDENTIAL_CLIENT_ID }}
        prod-verifiablecredential-client-secret: ${{ secrets.PROD_VERIFIABLECREDENTIAL_CLIENT_SECRET }}
        prod-verifiablecredential-authorization-url: ${{ secrets.PROD_VERIFIABLECREDENTIAL_AUTHORIZATION_URL }}
        prod-verifiablecredential-token-url: ${{ secrets.PROD_VERIFIABLECREDENTIAL_TOKEN_URL }}
        plan: true
