name: Terraform Apply

on: workflow_dispatch

env:
  TF_VERSION: 1.1.4
  KEYCLOAK_DEV_URL: https://sso-keycloak-1-b861c7-test.apps.silver.devops.gov.bc.ca
  KEYCLOAK_TEST_URL: https://sso-keycloak-2-b861c7-test.apps.silver.devops.gov.bc.ca
  KEYCLOAK_PROD_URL: https://sso-keycloak-3-b861c7-test.apps.silver.devops.gov.bc.ca

jobs:
  terraform:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: bcgov/sso-requests-actions/actions/setup-terraform@v0.41.0
        with:
          context: ./terraform
          tf-version: ${{ env.TF_VERSION }}
          tf-s3-bucket: "xgr00q-dev-keycloak"
          tf-s3-bucket-key: "keycloak/silver"
          tf-s3-access-key: ${{ secrets.TF_S3_ACCESS_KEY }}
          tf-s3-secret-key: ${{ secrets.TF_S3_SECRET_KEY }}
          tf-s3-role-arn: ${{ secrets.TF_S3_ROLE_ARN }}
          kc-dev-url: ${{ env.KEYCLOAK_DEV_URL }}
          kc-test-url: ${{ env.KEYCLOAK_TEST_URL }}
          kc-prod-url: ${{ env.KEYCLOAK_PROD_URL }}
          kc-dev-secret: ${{ secrets.KEYCLOAK_DEV_CLIENT_SECRET }}
          kc-test-secret: ${{ secrets.KEYCLOAK_TEST_CLIENT_SECRET }}
          kc-prod-secret: ${{ secrets.KEYCLOAK_PROD_CLIENT_SECRET }}
          apply: true
